### ISSUE TITLE
Add support for Sendgrid transactional templates

### ISSUE THREAD

**Issue by pierluigi** [bitoiu/release-notify-action#1]
Instead of hard-coding the email body it would be awesome to add support for [transactional templates](https://sendgrid.com/docs/ui/sending-email/create-and-edit-transactional-templates/). 

The official [sendgrid-nodejs](https://github.com/sendgrid/sendgrid-nodejs/blob/master/use-cases/transactional-templates.md) repo has some instructions on how to do that with the NodeJS client based on Handlebars. We could then use the ` dynamic_template_data` object to attach event payload info.

Any interest on this?

**Comment by bitoiu** [comment]
I would love this as opt-in @pierluigi, so if someone just wants the basic funcionality the setup is still very straightforward. But for people taking this more seriously this would be a requirement for sure.

:octocat::heart:
